# Generated by Django 4.0.1 on 2022-08-27 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_orders_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.cart'),
        ),
    ]
