# Generated by Django 4.0.1 on 2022-08-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_orders_order_id_orders_id_orders_order_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='orders',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='item',
            field=models.CharField(default='', max_length=500),
        ),
    ]
