# Generated by Django 4.0.1 on 2022-08-30 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_orders_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='qty',
        ),
        migrations.AlterField(
            model_name='orders',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.cart'),
        ),
    ]
