# Generated by Django 4.0.1 on 2022-09-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_orders_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='dispatched',
            field=models.BooleanField(default=False),
        ),
    ]
