# Generated by Django 4.0.1 on 2022-09-13 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_tracker_deliveredtime_tracker_dispatchedtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='seller',
            name='contact',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
