# Generated by Django 4.0.1 on 2022-09-16 06:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_rename_rating_product_avgrating_alter_seller_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avgrating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
